wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    code_path: code/apnea_detection.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.8.5
      5: 0.10.33
      8:
      - 5
apnea_type:
  desc: null
  value: osa
base_model_path:
  desc: null
  value: base_model.ckpt
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: dreams
epochs:
  desc: null
  value: '30'
excerpt:
  desc: null
  value: '2'
learning_rate:
  desc: null
  value: 0.001
logger:
  desc: null
  value: true
model_type:
  desc: null
  value: cnn
results_file:
  desc: null
  value: results.csv
retrain:
  desc: null
  value: false
root_dir:
  desc: null
  value: .
sample_rate:
  desc: null
  value: 8
scale_factor_high:
  desc: null
  value: 10
scale_factor_low:
  desc: null
  value: 0.1
seconds_after_apnea:
  desc: null
  value: 5
seconds_before_apnea:
  desc: null
  value: '5'
skip_preprocess:
  desc: null
  value: false
slope_threshold:
  desc: null
  value: '5'
test_frac:
  desc: null
  value: 0.2
threshold:
  desc: null
  value: 0.5
